# frontend/Dockerfile
# (Este es un placeholder temporal)

# 1. Usar una imagen base de Node.js (Alpine es ligera)
FROM node:18-alpine

# 2. Establecer el directorio de trabajo
WORKDIR /app

# 3. Comando 'dummy' para mantener el contenedor vivo
#    (Luego lo cambiaremos por el 'npm run dev' de Next.js)
CMD ["tail", "-f", "/dev/null"]