"""Add strategic fields to workspace

Revision ID: 63e5eed20850
Revises: e4f1a9b2c3d5
Create Date: 2026-01-06 10:23:52.622945

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '63e5eed20850'
down_revision = 'e4f1a9b2c3d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('conversations', 'has_proposal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'0'"))
    op.create_index('idx_user_updated', 'conversations', ['user_id', 'updated_at'], unique=False)
    op.drop_constraint(op.f('documents_ibfk_2'), 'documents', type_='foreignkey')
    op.create_foreign_key(None, 'documents', 'conversations', ['conversation_id'], ['id'], ondelete='CASCADE')
    op.add_column('workspaces', sa.Column('country', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('client_company', sa.String(length=200), nullable=True))
    op.add_column('workspaces', sa.Column('operation_name', sa.String(length=200), nullable=True))
    op.add_column('workspaces', sa.Column('tvt', sa.Float(), nullable=True))
    op.add_column('workspaces', sa.Column('tech_stack', sa.JSON(), nullable=True))
    op.add_column('workspaces', sa.Column('opportunity_type', sa.String(length=50), nullable=True))
    op.add_column('workspaces', sa.Column('estimated_price', sa.Float(), nullable=True))
    op.add_column('workspaces', sa.Column('estimated_time', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('resource_count', sa.Integer(), nullable=True))
    op.add_column('workspaces', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('workspaces', sa.Column('objective', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workspaces', 'objective')
    op.drop_column('workspaces', 'category')
    op.drop_column('workspaces', 'resource_count')
    op.drop_column('workspaces', 'estimated_time')
    op.drop_column('workspaces', 'estimated_price')
    op.drop_column('workspaces', 'opportunity_type')
    op.drop_column('workspaces', 'tech_stack')
    op.drop_column('workspaces', 'tvt')
    op.drop_column('workspaces', 'operation_name')
    op.drop_column('workspaces', 'client_company')
    op.drop_column('workspaces', 'country')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.create_foreign_key(op.f('documents_ibfk_2'), 'documents', 'conversations', ['conversation_id'], ['id'], ondelete='SET NULL')
    op.drop_index('idx_user_updated', table_name='conversations')
    op.alter_column('conversations', 'has_proposal',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    # ### end Alembic commands ###
