"""Add proposal model for scenarios

Revision ID: d7f1dfa45879
Revises: 63e5eed20850
Create Date: 2026-01-06 10:27:57.398325

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd7f1dfa45879'
down_revision = '63e5eed20850'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proposals',
    sa.Column('id', mysql.CHAR(length=36), nullable=False),
    sa.Column('workspace_id', mysql.CHAR(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('tech_stack', sa.JSON(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('estimated_time', sa.String(length=100), nullable=True),
    sa.Column('resource_count', sa.Integer(), nullable=True),
    sa.Column('objective', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    # ### end Alembic commands ###
